// src/pages/Terms.tsx
import React from "react";

const Terms = () => {
  return (
    <div className="prose max-w-3xl mx-auto py-16 px-4">
      <h1 className="text-4xl font-bold mb-6">Terms and Conditions</h1>
      <p><strong>Effective Date:</strong> [Insert Date]</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions...</p>

      <h2>2. Description of the Service</h2>
      <p>Alivoro allows users to upload illustrations or images and generate animated video content based on those images using AI technology...</p>

      <h2>3. AI-Generated Content Disclaimer</h2>
      <p>The video results generated by our Service are created by AI and are highly variable...</p>

      <h2>4. No Refund Policy</h2>
      <p><strong>All sales are final. Refunds are not available under any circumstances.</strong>...</p>

      <h2>5. User Responsibility</h2>
      <p>You are solely responsible for ensuring you have the legal right to upload and use the image(s) provided...</p>

      <h2>6. Intellectual Property</h2>
      <p>All AI-generated videos are delivered for personal use only...</p>

      <h2>7. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, we are not liable for any loss of profits, data, or use...</p>

      <h2>8. Changes to Terms</h2>
      <p>We may update these Terms at any time...</p>

      <h2>9. Governing Law</h2>
      <p>These Terms are governed by and construed in accordance with the laws of [Insert Country or Jurisdiction]...</p>

      <h2>10. Contact Us</h2>
      <p>📧 <strong>[Insert your contact email]</strong></p>
    </div>
  );
};

export default Terms;
