import React from "react";

const Terms = () => {
  return (
    <div className="max-w-4xl mx-auto py-20 px-4 text-gray-900">
      <h1 className="text-4xl font-bold mb-6 text-center">Terms and Conditions</h1>

      <p><strong>Effective Date:</strong> July 16, 2025</p>

      <h2 className="mt-6 font-semibold text-lg">1. Acceptance of Terms</h2>
      <p>
        By accessing or using the Alivoro website or services, you agree to be bound by these Terms and Conditions. If you do not agree, you may not use our services.
      </p>

      <h2 className="mt-6 font-semibold text-lg">2. Description of the Service</h2>
      <p>
        Alivoro allows users to upload children’s drawings or other artwork and generate animated videos using AI technology based on those images.
      </p>

      <h2 className="mt-6 font-semibold text-lg">3. AI-Generated Content Disclaimer</h2>
      <p>
        All videos are generated by artificial intelligence and may vary in style, quality, and accuracy. Results are not guaranteed and may not reflect exact expectations.
      </p>

      <h2 className="mt-6 font-semibold text-lg">4. No Refund Policy</h2>
      <p className="text-red-700 font-semibold">
        All sales are final. Refunds are not available under any circumstances.
      </p>
      <p>
        Since the videos are generated using AI based on user-provided images, and due to the creative variability of the process, no refunds will be issued for dissatisfaction with the result.
      </p>

      <h2 className="mt-6 font-semibold text-lg">5. User Responsibility</h2>
      <p>
        You are responsible for ensuring you have the legal right to upload and use any image submitted. Alivoro is not liable for content uploaded without proper permissions.
      </p>

      <h2 className="mt-6 font-semibold text-lg">6. Intellectual Property</h2>
      <p>
        All generated content is intended for personal, non-commercial use only. You may not resell or redistribute the video without written permission.
      </p>

      <h2 className="mt-6 font-semibold text-lg">7. Limitation of Liability</h2>
      <p>
        Alivoro shall not be liable for any indirect, incidental, or consequential damages. Our maximum liability shall not exceed the amount paid for the service.
      </p>

      <h2 className="mt-6 font-semibold text-lg">8. Changes to Terms</h2>
      <p>
        We reserve the right to update these Terms at any time. Changes will be posted on this page and become effective immediately upon publication.
      </p>

      <h2 className="mt-6 font-semibold text-lg">9. Governing Law</h2>
      <p>
        These Terms are governed by and interpreted according to the laws of Latvia or the country of the service operator.
      </p>

      <h2 className="mt-6 font-semibold text-lg">10. Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us at: <strong>alivorolive@gmail.com</strong>
      </p>
    </div>
  );
};

export default Terms;
